#!/usr/bin/env bash
#
# Example command to test Github Actions locally.
# Dependencies:
# - act (https://github.com/nektos/act)
# - gh (https://cli.github.com/)

act -W .github/workflows/build.yml \
    --action-offline-mode \
    -s GITHUB_TOKEN="$(gh auth token)" \
    -e .github/workflows/act/repository_dispatch.json \
    --var-file .github/workflows/act/vars \
    --env GITHUB_REPOSITORY=raulparada/dok-noord-arena
