name: "Build and deploy"
on:
    workflow_dispatch:
    repository_dispatch:
        types:
            - matchmaking
    push:
        branches:
            - main

permissions:
    contents: write
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            # Setup.
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  cache: "pip"
            - run: pip install -e .

            # Dispatches.
            - if: github.event_name == 'repository_dispatch'
              run: |
                  echo "repository dispatch: github.event.client_payload: ${{ github.event.client_payload || '' }}"
                  echo "repository dispatch: github.event.action: ${{ github.event.action || 'unknown' }}"

                  if [[ "${{ github.event.action }}" == "matchmaking" ]]; then
                    echo "Handling matchmaking event"
                    echo "${{ github.event.client_payload.data }}" > .matchmaking.txt
                    echo "matchmaking file contents: $(cat .matchmaking.txt)"
                    python main.py matchmaking .matchmaking.txt
                  fi

            # Build.
            - env:
                  CI_PUBLIC_TOKEN: ${{ secrets.DOKNOORD_CI_PUBLIC_TOKEN }}
              run: |
                  python main.py build
                  echo "$CI_PUBLIC_TOKEN" > site/ci_public_token

            # Deploy.
            - name: Setup Pages
              uses: actions/configure-pages@v5
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "site"
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4

            # Commit data changes (from dispatches).
            - if: github.event_name == 'workflow_dispatch'
              uses: EndBug/add-and-commit@v9
              with:
                  default_author: github_actions
                  add: data
                  message: 'ci: auto-commit ${{ github.run_id }}'
