on:
    repository_dispatch:
        types:
            - matchmaking
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Setup.
            - uses: actions/checkout@v4
            #   with:
            #       token: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/setup-python@v5
              with:
                  cache: "pip"
            - run: pip install .
            # Dispatches.
            - if: github.event_name == 'repository_dispatch'
              run: |
                  echo "repository dispatch: payload: ${{ github.event.client_payload || 'no payload' }}"
                  echo "repository dispatch: action: ${{ github.event.action || 'unknown action' }}"

                  if [[ "${{ github.event.action }}" == "matchmaking" ]]; then
                    echo "Handling matchmaking event"
                    echo "${{ toJson(github.event.client_payload).data }}" > .matchmaking.txt
                    python main.py matchmaking .matchmaking.txt
                  fi
            # Build.
            - if: github.event_name == 'push'
              env:
                  DOKNOORD_CI_PUBLIC_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  echo $DOKNOORD_CI_PUBLIC_TOKEN > docs/ci_public_token
                  python main.py build
            - uses: EndBug/add-and-commit@v9
              with:
                  default_author: github_actions
                  add: "['data', 'docs']"
