on:
    repository_dispatch:
        types:
            - matchmaking
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Setup.
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  cache: "pip"
            - run: pip install .
            # Action
            - run: |
                  echo "client payload: ${{ github.event.client_payload || 'no payload'}}"
                  python models.py
            - uses: EndBug/add-and-commit@v9
              with:
                  default_author: github_actions
                  add: docs
